name: Azure Web App CI/CD

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: deployWebapptest
  AZURE_WEBAPP_PACKAGE_PATH: ./

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm run test
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
